name: CI - NestJS

on:
  push:
    branches: [main, development]
  # pull_request:
  #   branches: [main, development]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Descarga el código del repo
      - name: Checkout app
        uses: actions/checkout@v4

      # 2️⃣ Configura Node.js
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.1
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install pnpm
        run: npm install -g pnpm@latest-10

      # 3️⃣ Instala dependencias
      - name: Install dependencies
        run: pnpm ci

      # 4️⃣ Ejecuta los tests de NestJS
      - name: Run tests
        run: pnpm run test --if-present

      # 5️⃣ Compila la app (verifica que build funcione)
      - name: Build NestJS app
        run: pnpm run build
